[build]
  # Directory to change to before starting a build (frontend subfolder)
  base = "frontend"
  
  # Directory that contains the deploy-ready HTML files and assets (relative to base)
  publish = "build"
  
  # Build command to run from the frontend directory
  command = "npm ci && npm run build"

[build.environment]
  # Node version for build
  NODE_VERSION = "18"
  
  # Prevent npm from running audit during build
  NPM_FLAGS = "--no-audit --no-fund"
  
  # Ignore CI warnings that could fail the build
  CI = "false"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Optimize images and assets
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true 